steps:
  - name: 'gcr.io/connectedcars-staging/cloudbuilder-wrapper.master'
    args: ['--secret-build-vars=NPM_TOKEN', '--build-vars=COMMIT_SHA,BRANCH_NAME', '--build-timeout=60m', '--update-url=https://build-api.connectedcars.io/cloudbuilder', '--skip-push']
    secretEnv:
      - 'NPM_TOKEN'
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'
secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
  secretEnv:
    NPM_TOKEN: CiQAg7wCPewIVIbfIFEcQIzhDPtFwwkVhuKsZz27ikGInbEjyrcSTABefMgezLQ+uMbN3cBIleg8ogOwhKOWV/99N9Ra9HNnfwCA6n7aL443W6eiEQavWArDqlS57K0FbW0BRd+JfShkXBCojePXbCto3X8=
timeout: 3600s
