steps:
  - name: 'gcr.io/connectedcars-staging/cloudbuilder-wrapper.master'
    args: ['--build-vars=COMMIT_SHA,BRANCH_NAME', '--build-timeout=60m', '--update-url=https://build-api.connectedcars.io/cloudbuilder', '--skip-push']
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'
timeout: 3600s
